const colors = {
  color1: [
    { value: "1", text: "1 Brown", class: "bg-amber-700", hexColor: "#964B00" },
    { value: "2", text: "2 Red", class: "w3-red", hexColor: "#FF0000" },
    { value: "3", text: "3 Orange", class: "w3-orange", hexColor: "#FFA500" },
    { value: "4", text: "4 Yellow", class: "w3-yellow", hexColor: "#FFFF00" },
    { value: "5", text: "5 Green", class: "w3-green", hexColor: "#008000" },
    { value: "6", text: "6 Blue", class: "w3-blue", hexColor: "#0000FF" },
    { value: "7", text: "7 Violet", class: "w3-purple", hexColor: "#800080" },
    { value: "8", text: "8 Gray", class: "w3-gray", hexColor: "#808080" },
    { value: "9", text: "9 White", class: "w3-white", hexColor: "#FFFFFF" },
  ],
  color2: [
    { value: "0", text: "0 Black", class: "w3-black", hexColor: "#000000" },
    { value: "1", text: "1 Brown", class: "bg-amber-700", hexColor: "#964B00" },
    { value: "2", text: "2 Red", class: "w3-red", hexColor: "#FF0000" },
    { value: "3", text: "3 Orange", class: "w3-orange", hexColor: "#FFA500" },
    { value: "4", text: "4 Yellow", class: "w3-yellow", hexColor: "#FFFF00" },
    { value: "5", text: "5 Green", class: "w3-green", hexColor: "#008000" },
    { value: "6", text: "6 Blue", class: "w3-blue", hexColor: "#0000FF" },
    { value: "7", text: "7 Violet", class: "w3-purple", hexColor: "#800080" },
    { value: "8", text: "8 Gray", class: "w3-gray", hexColor: "#808080" },
    { value: "9", text: "9 White", class: "w3-white", hexColor: "#FFFFFF" },
  ],
  multiply: [
    { value: "0", text: "×1 Black", class: "w3-black", hexColor: "#000000" },
    {
      value: "1",
      text: "×10 Brown",
      class: "bg-amber-700",
      hexColor: "#964B00",
    },
    { value: "2", text: "×100 Red", class: "w3-red", hexColor: "#FF0000" },
    { value: "3", text: "×1k Orange", class: "w3-orange", hexColor: "#FFA500" },
    {
      value: "4",
      text: "×10k Yellow",
      class: "w3-yellow",
      hexColor: "#FFFF00",
    },
    { value: "5", text: "×100k Green", class: "w3-green", hexColor: "#008000" },
    { value: "6", text: "×1M Blue", class: "w3-blue", hexColor: "#0000FF" },
    {
      value: "7",
      text: "×10M Violet",
      class: "w3-purple",
      hexColor: "#800080",
    },
    { value: "8", text: "×100M Gray", class: "w3-gray", hexColor: "#808080" },
    { value: "9", text: "×1G White", class: "w3-white", hexColor: "#FFFFFF" },
    { value: "-1", text: "÷10 Gold", class: "w3-amber", hexColor: "#FFC107" },
    {
      value: "-2",
      text: "÷100 Silver",
      class: "w3-blue-gray",
      hexColor: "#607D8B",
    },
  ],
  tolerance: [
    {
      value: "5",
      text: "± 5% Gold",
      class: "bg-yellow-500",
      hexColor: "#FFC107",
      eSeries: 96,
    },
    {
      value: "10",
      text: "± 10% Silver",
      class: "bg-gray-500",
      hexColor: "#607D8B",
      eSeries: 12,
    },
    {
      value: "20",
      text: "± 20% None",
      class: "bg-white-200",
      hexColor: "#FFFFFF",
      eSeries: 6,
    },
  ],
};

export default colors;
